
import __ASTRO_IMAGE_IMPORT_usSJm from "@books/dance-dance-dance.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fbooks.json";
import __ASTRO_IMAGE_IMPORT_2lGbFr from "@books/hiroshige.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fbooks.json";
import __ASTRO_IMAGE_IMPORT_Z1jd3Az from "@books/look-homeward-angel.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fbooks.json";
import __ASTRO_IMAGE_IMPORT_ggful from "@books/lost-in-the-forest.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fbooks.json";
import __ASTRO_IMAGE_IMPORT_Z2samPl from "@books/norwegian-wood.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fbooks.json";
import __ASTRO_IMAGE_IMPORT_2ixtvl from "@books/the-city-and-its-uncertain-walls.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fbooks.json";
import __ASTRO_IMAGE_IMPORT_woTYm from "@books/too-loud-a-solitude.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fbooks.json";
import __ASTRO_IMAGE_IMPORT_1hrdiu from "@books/white-light.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fbooks.json";
import __ASTRO_IMAGE_IMPORT_Z218tko from "@albums/beyond-the-sea-of-ghosts.jpg?astroContentImageFlag=&importer=src%2Fdata%2Falbums.json";
import __ASTRO_IMAGE_IMPORT_jBc4Y from "@albums/crystal-maze.jpg?astroContentImageFlag=&importer=src%2Fdata%2Falbums.json";
import __ASTRO_IMAGE_IMPORT_Zr7Pjh from "@albums/early-rains.jpg?astroContentImageFlag=&importer=src%2Fdata%2Falbums.json";
import __ASTRO_IMAGE_IMPORT_WDqmd from "@albums/far-lands.jpg?astroContentImageFlag=&importer=src%2Fdata%2Falbums.json";
import __ASTRO_IMAGE_IMPORT_163t0I from "@albums/morning-star.jpg?astroContentImageFlag=&importer=src%2Fdata%2Falbums.json";
import __ASTRO_IMAGE_IMPORT_1cC11v from "@albums/under-apen-himmel.jpg?astroContentImageFlag=&importer=src%2Fdata%2Falbums.json";
import __ASTRO_IMAGE_IMPORT_15mTz3 from "@albums/winds-and-windows.jpg?astroContentImageFlag=&importer=src%2Fdata%2Falbums.json";
import __ASTRO_IMAGE_IMPORT_Zsy2Eg from "@images/a-kitchen-in-athens.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fa-kitchen-in-athens.mdx";
import __ASTRO_IMAGE_IMPORT_1WACy0 from "@images/exploring-the-acropolis-of-athens/featured.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fexploring-the-acropolis-of-athens.mdx";
import __ASTRO_IMAGE_IMPORT_Z1Lj1XK from "@images/hills-of-bath-somerset/featured.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fhills-of-bath-somerset.mdx";
import __ASTRO_IMAGE_IMPORT_1RhpJi from "@images/norwegian-church-at-cardiff-bay-in-march/featured.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fnorwegian-church-at-cardiff-bay-in-march.mdx";
export default new Map([["@books/dance-dance-dance.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fbooks.json", __ASTRO_IMAGE_IMPORT_usSJm], ["@books/hiroshige.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fbooks.json", __ASTRO_IMAGE_IMPORT_2lGbFr], ["@books/look-homeward-angel.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fbooks.json", __ASTRO_IMAGE_IMPORT_Z1jd3Az], ["@books/lost-in-the-forest.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fbooks.json", __ASTRO_IMAGE_IMPORT_ggful], ["@books/norwegian-wood.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fbooks.json", __ASTRO_IMAGE_IMPORT_Z2samPl], ["@books/the-city-and-its-uncertain-walls.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fbooks.json", __ASTRO_IMAGE_IMPORT_2ixtvl], ["@books/too-loud-a-solitude.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fbooks.json", __ASTRO_IMAGE_IMPORT_woTYm], ["@books/white-light.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fbooks.json", __ASTRO_IMAGE_IMPORT_1hrdiu], ["@albums/beyond-the-sea-of-ghosts.jpg?astroContentImageFlag=&importer=src%2Fdata%2Falbums.json", __ASTRO_IMAGE_IMPORT_Z218tko], ["@albums/crystal-maze.jpg?astroContentImageFlag=&importer=src%2Fdata%2Falbums.json", __ASTRO_IMAGE_IMPORT_jBc4Y], ["@albums/early-rains.jpg?astroContentImageFlag=&importer=src%2Fdata%2Falbums.json", __ASTRO_IMAGE_IMPORT_Zr7Pjh], ["@albums/far-lands.jpg?astroContentImageFlag=&importer=src%2Fdata%2Falbums.json", __ASTRO_IMAGE_IMPORT_WDqmd], ["@albums/morning-star.jpg?astroContentImageFlag=&importer=src%2Fdata%2Falbums.json", __ASTRO_IMAGE_IMPORT_163t0I], ["@albums/under-apen-himmel.jpg?astroContentImageFlag=&importer=src%2Fdata%2Falbums.json", __ASTRO_IMAGE_IMPORT_1cC11v], ["@albums/winds-and-windows.jpg?astroContentImageFlag=&importer=src%2Fdata%2Falbums.json", __ASTRO_IMAGE_IMPORT_15mTz3], ["@images/a-kitchen-in-athens.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fa-kitchen-in-athens.mdx", __ASTRO_IMAGE_IMPORT_Zsy2Eg], ["@images/exploring-the-acropolis-of-athens/featured.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fexploring-the-acropolis-of-athens.mdx", __ASTRO_IMAGE_IMPORT_1WACy0], ["@images/hills-of-bath-somerset/featured.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fhills-of-bath-somerset.mdx", __ASTRO_IMAGE_IMPORT_Z1Lj1XK], ["@images/norwegian-church-at-cardiff-bay-in-march/featured.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fnorwegian-church-at-cardiff-bay-in-march.mdx", __ASTRO_IMAGE_IMPORT_1RhpJi]]);
		